experiment_name: "local_inference_and_segmentation"
output_dir: "data/results/exp3/001_inference_environment_vs_object"

# Fixed Parameters
fixed_params:
  verbose: True
  nb_iter_metric: 10000
  nb_iter_inference_per_object: 200
  image_env_path: "data/environments/NatWdwF.jpeg"
  camera_side_size: 10
  actions: [0, 1, 2, 3, 4]
  transformations: [0, 1, 2, 3, 4]
  snr_array: [30, 40, 60]


varying_param:
  nb_seeds: 100 #from 0 to 100
  object_side_size: [1, 2, 4, 6]
  update_rate: .8
  initial_objecthood_probability: .2
  object_rejection_threshold: .2
  rejection_threshold: 6.


